### PR TITLE
Add some crawlers

### PR DESCRIPTION
**Pull request by aharbick**
User agents seen in my environment:

```
AWS Security Scanner
HaxerMen
kubectl/v1.12.0 (linux/amd64) kubernetes/0ed3388
NetSystemsResearch studies the availability of various services across the internet. Our website is netsystemsresearch.com
```

### CODE REVIEW

**Comment by loadkpi** [comment]
Hello Andrew!

Thanks for your PR. Will it work for you to create the same PR for PHP lib (https://github.com/JayBizzle/Crawler-Detect)? The main reason for that is simple: this gem uses crawlers / exclusions / test data from PHP lib Crawler-Detect. So it will be hard to maintaine if we start to add our own crawlers data separately. 

Sorry that it is not clear from Readme. I will add a notice about adding new crawlers.

**Comment by aharbick** [comment]
No problem.  I created this: https://github.com/JayBizzle/Crawler-Detect/pull/347

Perhaps I was too hasty and didn't read carefully, but I don't recall seeing instructions on how to contribute to this library.  In the PHP library they had this: https://github.com/JayBizzle/Crawler-Detect/blob/master/CONTRIBUTING.md which github warned me about before creating my PR.

Thanks for maintaining this!

**Comment by JayBizzle** [comment]
>So it will be hard to maintaine if we start to add our own crawlers data separately.

Thanks for trying to keep the upstream up-to-date, it really will be beneficial for everyone 👍

**Comment by aharbick** [comment]
Thanks!

**Comment by loadkpi** [comment]
merged via https://github.com/loadkpi/crawler_detect/pull/18

Thanks, Andrew

**Pull request closed without merging**
